### ISSUE TITLE
[Request] EnderIO support

### ISSUE THREAD

**Issue by ajthemacboy** [CarrotCodes/EnderTech#67]
I'm somewhat irked by Thermal Expansion and it's over popularity. For this reason my pack doesn't have Thermal Expansion, and instead we promote Ender IO, Mekanism, and other similar mods that aren't used as much.

Thus I'd like EnderTech to work without ThermalExpansion, using EnderIO parts instead.

**Comment by carrotengineer** [comment]
Thermal Expansion isn't a hard dependency - if you don't include it, recipes are simply not defined.

The recommended way of setting recipes is to use MineTweaker to override them. Several of Jadedcat's FTB packs do this, if you're looking for examples.

**Comment by ajthemacboy** [comment]
Just realized there was an issue already open for this, sorry :)
